### ISSUE TITLE
README in docker

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/curatedMetagenomicAnalyses#15]
@lwaldron I want to clarify the content for the README file that will be in the file explorer on the left side of Jupyter Lab. Are these just the instructions to run the analyses?

We could just add that to the repository's README and then I could just copy that file up one level from the curatedMetagenomicAnalyses repository in the docker. If that's confusing, I can make a different README for the docker.

**Comment by lwaldron** [comment]
Yes I think you could just copy the README.md from one level up. Eventually we should include in it a table of contents of the analysis files and what they do.
