### ISSUE TITLE
Add link to paper and fix figure

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/curatedMetagenomicAnalyses#20]
I think we're missing a reference to a paper @paolinomanghi's notebook:

    The flag "-m" will attach the per-sample metadata available in curatedMetagenomicData 3 to their taxonomic 
    profiles. We now switch to a python 3 set of instructions that can be used to perform the main analysis of 
    Figure 2, panel a, of the paper "***".

And I think there's still some issue with the figure:

![screen_shot_notebook_figure](https://user-images.githubusercontent.com/1744257/126633280-d04d224a-d160-4523-9570-cfbd0cbeff6c.png)

**Comment by paolinomanghi** [comment]
I corrected the figure issues. The new one looks better, however I can't insert the reference in the paper right now, we have to submit it before.
