### ISSUE TITLE
login screen does not display properly

### ISSUE THREAD

**Issue by schifferl** [waldronlab/curatedMetagenomicAnalyses#27]
When I open http://app.orchestra.cancerdatasci.org/login in Chrome, I simply get a page that says "Welcome to the Orchestra platform" and nothing more. I had hoped to login and try the server; can this be fixed?

**Comment by jwokaty** [comment]
This isn't an issue with this repo. I was able to log in and then navigate to curated Metagenomic Analysis then start the container. Can you try with another browser? You should see two button, one to login with email and another with google.

**Comment by schifferl** [comment]
Thank you for the help @jwokaty! Changing browsers was all it took 🤦 , closing the issue.
