### ISSUE TITLE
get GHA building

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicAnalyses#3]

**Comment by lwaldron** [comment]
@jwokaty note I've created https://hub.docker.com/repository/docker/waldronlab/curatedmetagenomicanalyses, so with the secrets passed to the GHA, so unless I've missed something a successful build should also push an image there.

**Comment by lwaldron** [comment]
One other item to add to this issue, it seems like checks are getting duplicated, at least on a pull request? E.g. from the PR I just made to get rid of BiocCheck (https://github.com/waldronlab/curatedMetagenomicAnalyses/pull/10)

![image](https://user-images.githubusercontent.com/639942/125427421-8302b960-3b8e-44a1-b7ff-2b437d3fb293.png)

**Comment by jwokaty** [comment]
Closed by #10. We'll leave the duplication issue for now, but if we have time later, we can look at https://github.com/marketplace/actions/skip-duplicate-actions, which might help.
