### ISSUE TITLE
README.md links don't work from pkgdown

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicAnalyses#36]
In the pkgdown site (https://waldronlab.io/curatedMetagenomicAnalyses/index.html) The following links from the README.md file lead to waldronlab.io/ etc when they should lead to github.com/waldronlab/curatedMetagenomicAnalyses, and give "no content found" messages as a result:

### R Vignettes

* [Create datasets for machine learning](vignettes/MLdatasets.Rmd)
* [Exploration of the liver cirrhosis dataset](vignettes/explorecirrhosis.Rmd)
* [Meta-analysis of age-related microbial species using cMD3](vignettes/Age_metaanalysis_vignette.Rmd)
* [Meta-analysis of sex-related microbial species using cMD3](vignettes/Sex_metaanalysis_vignette.Rmd)
* [NUI Galway Metagenomics Workshop](vignettes/NUI-Galway-Metagenomics-Workshop.Rmd)

### Python Notebooks

* [Sex-related differences in the human microbiome using cMD3 and Python3](vignettes/sexContrastMicrobiomeAnalysis.ipynb)

### Supplementary Materials 

* [Installing Python dependencies in Linux](vignettes/installation.ipynb) (Python notebook)

**Comment by lwaldron** [comment]
The issue is that they work from github.com, but not from https://waldronlab.io/curatedMetagenomicAnalyses/index.html.  The easiest fix I can think of is just to put full paths in the README.md file, but maybe there is another fix?

**Comment by schifferl** [comment]
I think this is the correct approach – I can't think of another myself anyway. I made some updates to the links which can be committed directly from the pull request and then we'll merge #38.

**Comment by schifferl** [comment]
Closed by merging #38 (677f1be).
